name: continuous integration 

on:
  push:
    branches: [master] 

jobs:
  test_suite:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2 
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2 
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Checks
        run: |
          cd src
          flake8 --ignore=E501,F401,E402 .
      - name: Run Tests
        run: |
          cd src
          export DB_URI=postgresql+psycopg2://admin:admin@localhost:5432/spotify_ext
          python -m unittest discover tests/
